# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: tunogya
# "service" is the name of this project. This will also be added to your AWS resource names.
service: relay-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    UPSTASH_REDIS_REST_URL: ${env:UPSTASH_REDIS_REST_URL}
    UPSTASH_REDIS_REST_TOKEN: ${env:UPSTASH_REDIS_REST_TOKEN}
    ASTRADB_ENDPOINT: ${env:ASTRADB_ENDPOINT}
    ASTRADB_TOKEN: ${env:ASTRADB_TOKEN}

functions:
  autoglyphs:
    name: autoglyphs
    handler: src/autoglyphs.handler
    events:
      - httpApi:
          path: /autoglyphs
          method: get
  search:
    name: search
    handler: src/search.handler
    events:
      - httpApi:
          path: /search
          method: get